### PR TITLE
Am welcome to nashville

### PR DESCRIPTION
**Pull request by AliAbdulle**
Please check my code:

`git fetch --all
git checkout ..

run your server
Thanks!`

### CODE REVIEW

**Comment by anneraev** [comment]
Honestly, we can't really use this. It's virtually the same thing you and I worked on yesterday, only now its not compatible with the DOM manager stuff we also started. Also, the branch conflict fix seems to have introduced a new issue. The code won't run and I assume that has to do with how the script tags are arranged in index.html.

**Comment by AliAbdulle** [comment]
Please check my code:

`git fetch --all
git checkout ..

run your server
Thanks!`

**Comment by MeagMueller** [comment]
👍

**Comment by anneraev** [comment]
Conflicts are gone, thanks!

**Pull request merged**
