### PR TITLE
attaching zshrc and gitignore

### PR DESCRIPTION
**Pull request by samalpren**
Attached a file for aliases and for git ignore.
Make sure running correctly.
Please download NPM manager.
Test out.

### CODE REVIEW

**Comment by MeagMueller** [comment]
Ran Grunt, .gitignore looks fine 👍

**Comment by stephensenft21** [comment]
Code looks good. node_modules in gitignore

**Comment by anneraev** [comment]
Looks good to me. Install worked, everything appears to be there. I was able to run grunt and open up the json server and the http server. Good job, Sam! :)

**Comment by AliAbdulle** [comment]
worked fine to me 👍

**Pull request merged**
